import React, { useEffect, useMemo, useState } from 'react';
import { Header, Sidebar } from '../../component/Menu';
import { FiGitBranch, FiPlus, FiEdit3, FiPower, FiRefreshCw } from 'react-icons/fi';
import toast from 'react-hot-toast';
import { getFlowStatus, listFlows } from '../../api/flowBuilder';

export default function FlowList() {
  const [minimized, setMinimized] = useState(() => JSON.parse(localStorage.getItem('sidebarMinimized') || 'false'));
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false); const [projectId, setProjectId] = useState(''); const [flows, setFlows] = useState([]); const [activeId, setActiveId] = useState(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const user = JSON.parse(localStorage.getItem('userData') || '{}'); const id = user.selected_project_id || user.projects?.[0]?.project_id || ''; setProjectId(id); if (!id) return; const [list, status] = await Promise.all([listFlows(id), getFlowStatus(id)]); if (list.error) throw new Error(list.error); setFlows(list.data || []); setActiveId(status.active_flow?.flow_id || null); } catch (error) { toast.error(error?.message || 'Could not load flows'); } finally { setLoading(false); } };
  useEffect(() => { localStorage.setItem('sidebarMinimized', JSON.stringify(minimized)); load(); }, []);
  const groups = useMemo(() => ({ published: flows.filter((f) => f.status === 'published'), draft: flows.filter((f) => f.status === 'draft'), archived: flows.filter((f) => f.status === 'archived') }), [flows]);
  const openBuilder = (id) => { if (id) localStorage.setItem('flowBuilderOpenId', id); window.location.href = '/flow'; };
  return <div className="min-h-screen bg-slate-50 dark:bg-gray-900"><Header mobileMenuOpen={mobileMenuOpen} setMobileMenuOpen={setMobileMenuOpen} isMinimized={minimized} setIsMinimized={setMinimized}/><Sidebar mobileMenuOpen={mobileMenuOpen} setMobileMenuOpen={setMobileMenuOpen} isMinimized={minimized} setIsMinimized={setMinimized}/><main className={`pt-16 transition-all ${minimized ? 'md:pl-20' : 'md:pl-72'}`}><div className="p-4 md:p-8 max-w-8xl mx-auto"><div className="flex flex-wrap justify-between items-center gap-4 mb-6"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2"><FiGitBranch className="text-indigo-600"/> Flow Library</h1><p className="text-sm text-slate-500 mt-1">All conversation flows for the selected project.</p></div><div className="flex gap-2"><button onClick={load} className="btn-secondary"><FiRefreshCw/> Refresh</button><button onClick={() => openBuilder(null)} className="btn-primary"><FiPlus/> New flow</button></div></div>{loading ? <div className="p-12 text-center text-slate-500">Loading flows...</div> : <div className="space-y-6">{[['published','Published',groups.published],['draft','Drafts',groups.draft],['archived','Archived',groups.archived]].map(([key, label, items]) => <section key={key}><h2 className="text-sm font-bold uppercase tracking-wide text-slate-500 mb-3">{label} ({items.length})</h2>{items.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-400">No {label.toLowerCase()} flows.</div> : <div className="grid md:grid-cols-2 gap-4">{items.map((flow) => <div key={flow.flow_id} className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-slate-800">{flow.name}</h3><p className="text-xs text-slate-500 mt-1">Version {flow.version} · Updated {flow.modify_date || '—'}</p></div>{activeId === flow.flow_id && <span className="text-xs font-semibold text-emerald-600 flex items-center gap-1"><FiPower/> Active</span>}</div><div className="mt-4 flex gap-2"><button onClick={() => openBuilder(flow.flow_id)} className="inline-flex items-center gap-2 rounded-lg bg-indigo-50 px-3 py-2 text-sm font-medium text-indigo-700"><FiEdit3/> Open builder</button></div></div>)}</div>}</section>)}</div>}</div></main></div>;
}
